instalador ubuntu vuelve a funcionar (ver eAdventure-editor)

diff --git a/packaging/deb/eAdventure-editor b/packaging/deb/eAdventure-editor
--- a/packaging/deb/eAdventure-editor
+++ b/packaging/deb/eAdventure-editor
@@ -11,8 +11,28 @@ echo
 echo "    (C)2005-2012 e-UCM research group"
 
 JAVA_OPTS="$JAVA_OPTS -Xms256m -Xmx512m"
+EDITOR_HOME="$HOME/.eadventure"
 EADVENTURE_HOME="/usr/share/java/e-adventure/eadventure"
+CFG_EDITOR="config_editor.xml"
 JAR_NAME="eadventure-editor.jar"
+
+# If first use, create local editor working directory; bail if failure
+if ! [ -d "$EDITOR_HOME" ]; then
+  echo "$EDITOR_HOME not found - creating local installation"
+  if ! (\
+        mkdir "$EDITOR_HOME" && \
+        ln -s "$EADVENTURE_HOME"/* "$EDITOR_HOME" && \
+        rm "$EDITOR_HOME/$CFG_EDITOR" "$EDITOR_HOME/web" && \
+        cp -r "$EADVENTURE_HOME/$CFG_EDITOR" "$EADVENTURE_HOME/web" \
+           "$EDITOR_HOME") ; 
+    then
+    
+    echo "Error creating local installation; sorry :-("
+    #rm -rf $EDITOR_HOME
+  else
+    echo "Created local installation. You are ready to edit!".
+  fi
+fi  
 
 # Look for the right JVM to use
 
@@ -25,7 +45,7 @@ fi
 
 if [ -x "$JAVACMD" ] ; then
   OLDPWD=$(pwd)
-  cd "$EADVENTURE_HOME"
+  cd "$EDITOR_HOME"
   $JAVACMD $JAVA_OPTS -jar $JAR_NAME $@
   cd $OLDPWD
 else
